parameters:
#    svarog_blog.example.class: Svarog\BlogBundle\Example

services:
#    svarog_blog.example:
#        class: %svarog_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
