parameters:
#    svarog_panel.example.class: Svarog\PanelBundle\Example

services:
#    svarog_panel.example:
#        class: %svarog_panel.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
